// <auto-generated />
using System;
using DistLab2.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DistLab2.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20231024092707_Auctions_added2")]
    partial class Auctions_added2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DistLab2.Persistence.DAO.AuctionDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("StartingPrice")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuctionDbs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreationDate = new DateTime(2023, 10, 4, 11, 27, 7, 264, DateTimeKind.Local).AddTicks(6672),
                            Description = "lite hål dock",
                            EndDate = new DateTime(2023, 10, 23, 11, 27, 7, 264, DateTimeKind.Local).AddTicks(6722),
                            Name = "Fina hattar",
                            StartingPrice = 99,
                            Username = "agge@hotmail.com"
                        },
                        new
                        {
                            Id = -2,
                            CreationDate = new DateTime(2023, 10, 14, 11, 27, 7, 264, DateTimeKind.Local).AddTicks(6859),
                            Description = "Jag hittade den",
                            EndDate = new DateTime(2023, 10, 24, 11, 17, 7, 264, DateTimeKind.Local).AddTicks(6863),
                            Name = "Plånbok",
                            StartingPrice = 100,
                            Username = "algot@kth.com"
                        },
                        new
                        {
                            Id = -3,
                            CreationDate = new DateTime(2023, 10, 14, 11, 27, 7, 264, DateTimeKind.Local).AddTicks(6903),
                            Description = "lite jord medkommer",
                            EndDate = new DateTime(2023, 10, 24, 11, 17, 7, 264, DateTimeKind.Local).AddTicks(6906),
                            Name = "En kruka",
                            StartingPrice = 100,
                            Username = "emil@hotmale.com"
                        });
                });

            modelBuilder.Entity("DistLab2.Persistence.DAO.BidDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<double>("BidAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateOfBid")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.ToTable("BidDbs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AuctionId = -1,
                            BidAmount = 140.0,
                            DateOfBid = new DateTime(2023, 10, 22, 11, 27, 7, 264, DateTimeKind.Local).AddTicks(6728),
                            Username = "emil@hotmale.com"
                        },
                        new
                        {
                            Id = -2,
                            AuctionId = -1,
                            BidAmount = 200.0,
                            DateOfBid = new DateTime(2023, 10, 22, 23, 27, 7, 264, DateTimeKind.Local).AddTicks(6734),
                            Username = "popcorn@gmail.com"
                        },
                        new
                        {
                            Id = -3,
                            AuctionId = -2,
                            BidAmount = 501.0,
                            DateOfBid = new DateTime(2023, 10, 24, 10, 47, 7, 264, DateTimeKind.Local).AddTicks(6867),
                            Username = "emil@hotmale.com"
                        },
                        new
                        {
                            Id = -4,
                            AuctionId = -2,
                            BidAmount = 5800.0,
                            DateOfBid = new DateTime(2023, 10, 24, 11, 7, 7, 264, DateTimeKind.Local).AddTicks(6870),
                            Username = "algot@hotmail.se"
                        },
                        new
                        {
                            Id = -5,
                            AuctionId = -2,
                            BidAmount = 501.0,
                            DateOfBid = new DateTime(2023, 10, 24, 10, 47, 7, 264, DateTimeKind.Local).AddTicks(6910),
                            Username = "popcorn@gmail.com"
                        },
                        new
                        {
                            Id = -6,
                            AuctionId = -2,
                            BidAmount = 5800.0,
                            DateOfBid = new DateTime(2023, 10, 24, 11, 7, 7, 264, DateTimeKind.Local).AddTicks(6913),
                            Username = "algot@hotmail.se"
                        });
                });

            modelBuilder.Entity("DistLab2.Persistence.DAO.BidDb", b =>
                {
                    b.HasOne("DistLab2.Persistence.DAO.AuctionDb", "AuctionDb")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuctionDb");
                });

            modelBuilder.Entity("DistLab2.Persistence.DAO.AuctionDb", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
